name: Generate PDF Resumes
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate English PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: resume_en.md
          output_dir: output
          build_html: false
        continue-on-error: true

      - name: Generate Turkish PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: resume_tr.md
          output_dir: output
          build_html: false
        continue-on-error: true

      - name: Generate French PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: resume_fr.md
          output_dir: output
          build_html: false
        continue-on-error: true

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Resumes-Muhammed-Furkan-Demirci
          path: output/
